### ISSUE TITLE
SyntaxError about Exception.

### ISSUE THREAD

**Issue by kimkyeonghun** [yorks/mpfhandler#1]
```bash
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    runner.run()
  File "/home/kyeonghun.kim/BERTopic/command.py", line 76, in run
    cmd.clear()
  File "/home/kyeonghun.kim/BERTopic/command.py", line 14, in clear
    self.runner.clear()
  File "/home/kyeonghun.kim/BERTopic/log.py", line 70, in clear
    self.logger.exception("ERROR")
  File "/home/kyeonghun.kim/BERTopic/log.py", line 17, in logger
    self._logger = self.get_logger(self.logger_name)
  File "/home/kyeonghun.kim/BERTopic/log.py", line 39, in get_logger
    from mpfhandler import MultProcTimedRotatingFileHandler
  File "/home/kyeonghun.kim/anaconda3/envs/topic/lib/python3.8/site-packages/mpfhandler.py", line 295
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

I think 'except Exception as e' is correct.

**Comment by yorks** [comment]
sorry,  python3 not support, but you can try latest : [mpfhandler.py](https://github.com/yorks/mpfhandler/raw/master/src/mpfhandler.py)

**Comment by kimkyeonghun** [comment]
Ok. I will try it.
